### ISSUE TITLE
Native component for "BlurView" does not exist on IOS

### ISSUE THREAD

**Issue by Hancoson** [react-native-community/react-native-blur#249] opened 2017-12-01 09:23 UTC
```
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-blur": "^3.2.2"
```
![image](https://user-images.githubusercontent.com/5474666/33476224-33ba74da-d6bc-11e7-9adf-f2957de3f9b8.png)

**Comment by sellmeadog** [comment] 2017-12-02 00:10
I'm receiving the same error with the same package versions for react, react-native and react-native-blur.

**Comment by jskidd3** [comment] 2017-12-07 18:06
Same error. Did you manage to resolve?

**Comment by tmaly1980** [comment] 2017-12-07 20:26
Did you run `react-native link` and recompile your binary (`react-native run-ios`)?

**Comment by sellmeadog** [comment] 2017-12-07 20:27
Yes. Linked with no errors.

**Comment by jskidd3** [comment] 2017-12-07 20:34
I also linked with no errors. I've taken a look at the project in Xcode and can't see anything referring to blur there. Shouldn't there be `RCTBlur.xcodeproject`? Perhaps link is silently failing?

**Comment by tmaly1980** [comment] 2017-12-07 20:50
It's RNBlur.xcodeproj . I had zero problem getting it working, and it's there in the Libraries (at the end for me)

**Comment by jskidd3** [comment] 2017-12-07 21:03
Strange. Do you mind sharing your project's `package.json` dependencies just so I can check on your versions?

**Comment by tmaly1980** [comment] 2017-12-07 21:05
"react-native-blur": "^3.2.2",

**Comment by jskidd3** [comment] 2017-12-07 21:10
No luck with the reinstall. Could you let me know your `react` and `react-native` versions too, please?

**Comment by tmaly1980** [comment] 2017-12-07 21:14
When you say "no luck", do you mean you aren't getting the RNBlur.xcodeproj included?

How about manually linking as a last resort? My guess is just import the RNBlur.xcodeproj into Libraries and add 'libRNBlur.a' to Build Phases -> Link Binary with Libraries

```
  "dependencies": {
    "apisauce": "^0.14.0",
    "bugsnag-react-native": "^2.7.3",
    "format-json": "^1.0.3",
    "lodash": "^4.17.2",
    "native-base": "^2.3.3",
    "prop-types": "^15.5.10",
    "querystringify": "0.0.4",
    "ramda": "^0.24.1",
    "react": "16.0.0-beta.5",
    "react-native": "0.49.3",
    "react-native-animatable": "^1.2.4",
    "react-native-audio-toolkit": "git+https://github.com/tmaly1980/react-native-audio-toolkit.git",
    "react-native-blur": "^3.2.2",
    "react-native-code-push": "^5.1.3-beta",
    "react-native-config": "^0.6.0",
    "react-native-drawer": "^2.3.0",
    "react-native-fast-image": "^2.0.1",
    "react-native-gesture-view": "estate/react-native-gesture-view",
    "react-native-global-props": "^1.1.3",
    "react-native-image-progress": "^1.0.1",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-music-control": "^0.4.13",
    "react-native-progress": "^3.4.0",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-vector-icons": "4.3.0",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^2.13.2",
    "redux-persist": "^4.1.0",
    "redux-saga": "^0.15.6",
    "reduxsauce": "0.4.1",
    "seamless-immutable": "^7.0.1"
  },
  "devDependencies": {
    "@storybook/addon-storyshots": "^3.2.3",
    "@storybook/react-native": "^3.2.3",
    "babel-eslint": "7.1.1",
    "babel-jest": "21.2.0",
    "babel-plugin-ignite-ignore-reactotron": "^0.3.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react-native": "3.0.2",
    "enzyme": "^2.6.0",
    "husky": "^0.13.1",
    "ignite-animatable": "^1.0.0",
    "ignite-ir-boilerplate": "^2.2.2",
    "ignite-standard": "^1.0.0",
    "ignite-vector-icons": "^1.1.0",
    "jest": "21.2.1",
    "mockery": "^2.0.0",
    "react-addons-test-utils": "~15.4.1",
    "react-dom": "16.0.0-alpha.12",
    "react-test-renderer": "16.0.0-beta.5",
    "reactotron-react-native": "^1.12.0",
    "reactotron-redux": "^1.11.1",
    "reactotron-redux-saga": "^1.11.1",
    "snazzy": "^7.0.0",
    "standard": "10.0.2"
  },
```

**Comment by sellmeadog** [comment] 2017-12-07 21:43
I think the key is the react-native version. The package seemed to work fine until react-native 0.50.3

At least for me.

**Comment by tmaly1980** [comment] 2017-12-07 21:49
Yeah I’ve just upgraded to 0.50.0 and it still works. Generally I would want to stay at least a minor version behind because third party libraries break, as much as they shouldn’t, and often don’t get patched for months, depending on how active the developers still are (ie whether or not they’re still using it in an active project or have moved on). The woes of React Native development. =(

**Comment by jskidd3** [comment] 2017-12-07 21:59
Thanks a lot. I'll give this a go tomorrow and appreciate the advice about staying a minor version behind!

**Comment by jd20** [comment] 2017-12-22 06:11
I encountered this same issue (with 51.0). Adding manually didn't succeed for me, but I found if I rebuilt the project from scratch (install and link react-native-blur before any other dependencies), everything worked fine. So that's one possible workaround.

**Comment by Kureev** [comment] 2018-01-05 09:28
👋 Hi there.

Indeed, I have very different activities now, but it doesn't mean that library doesn't work though. I checked 

```
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-blur": "^3.2.2"
```

on the blank project and it worked for me 🤔 . I'm about to close it until there will be a solid reproduction case.

**Closed by Kureev** 2018-01-05 09:28 UTC

**Comment by RUIFERNANDE5** [comment] 2018-01-05 19:07
@Kureev RN is currently on 0.52-RC, I have the same problem using the stable version 0.51.
Thats a solid reproduction case 🤔

**Comment by RUIFERNANDE5** [comment] 2018-01-05 19:08
+1 using 0.51

**Comment by SeOcSa** [comment] 2018-01-07 03:04
I have the same issue using 
"react": "16.0.0",
"react-native": "0.51.0",
"react-native-blur": "^3.2.2".

I think this case should be reopen.

**Comment by drewandre** [comment] 2018-01-22 20:45
I also couldn't use this awesome library due to this issue.
```
    "react": "16.0.0",
    "react-native": "0.50.4",
    "react-native-blur": "^3.2.2",
```

**Comment by ashleydw** [comment] 2018-02-05 20:38
Same here, but adding `libRNBlur.a` to the Build Phases fixes it (on RN 0.52.0)

**Comment by Shamash2014** [comment] 2018-02-05 21:39
Fixes on RN 0.53 also

**Comment by raztud** [comment] 2018-08-30 13:29
same issue, 
```"dependencies": {
    "expo": "^27.0.1",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-blur": "^3.2.2",
    "react-native-calendars": "^1.20.0",
    "react-native-elements": "^0.19.1",
    "react-native-ui-lib": "^3.3.223",
    "react-navigation": "^2.12.1"
  }```

**Comment by Nagibaba** [comment] 2018-10-11 14:59
add `new BlurViewPackage()` to your `getPackages()` function in `MainApplication.java`

**Comment by myjbuilddream** [comment] 2018-11-15 07:34
Fixes on RN 0.57.4 also
![image](https://user-images.githubusercontent.com/27722680/48537246-f3338a80-e8eb-11e8-98a6-71bf600fa135.png)

**Comment by jakubgrzelak** [comment] 2018-12-21 05:10
The same problem as above 👍

**Comment by ericvicenti** [comment] 2019-01-15 20:18
Confirmed that this issue still exists on latest RN. If you see this, go into Xcode, add blur xcode project from node modules to the "Libraries" folder (if its not already there), then go add `libRNBlur.a` to the "Link Binary with Library" section under "Build Phases"

@Kureev, can we re-open or re-file this? The RN link configuration seems busted.
