### ISSUE TITLE
Example App Not Working RN 0.40 

### ISSUE THREAD

**Issue by moerabaya** [react-native-community/react-native-blur#158] opened 2017-02-19 09:36 UTC
Down below what I'm receiving, I used the example code in my app and it's not working.
iOS 10.2
React Native 0.40

<img width="487" alt="screen shot 1438-05-22 at 11 33 58 am" src="https://cloud.githubusercontent.com/assets/12199727/23101225/56baa82a-f697-11e6-8d7f-478c08160396.png">

**Comment by Kureev** [comment] 2017-02-19 13:13
Please, take a look on `hotfix/example` branch. It's a known issue, and we're currently working on it (iOS is fixed, but Android still fails)

**Comment by Kureev** [comment] 2017-02-19 13:14
closed as duplicate of https://github.com/react-native-community/react-native-blur/issues/149

**Closed by Kureev** 2017-02-19 13:14 UTC
