### ISSUE TITLE
[bug] Blur effect seems to double or reapply when content changes inside of it

### ISSUE THREAD

**Issue by dwilt** [react-native-community/react-native-blur#117] opened 2016-11-09 23:23 UTC
See the movie here: https://dl.dropboxusercontent.com/u/4751361/react-native-double-blur-bug.mov

For some reason when the search results pop in, it gets more blurry and darker. Keep an eye on the DIRT MEN image the entire time starting from the beginning of the video. The blur shows once I search - which is correct and you can see the loader. But when it finishes loading and the content pops in, you can see it get darker. Any ideas?

**Comment by Kureev** [comment] 2016-11-11 05:35
Hi @dwilt! I think I need to validate your assumption first. My gut feeling is that you have two different BlurViews over each other. Can you be so kind to check it?

**Comment by dwilt** [comment] 2016-11-12 05:06
@Kureev thanks for the response. I did check - it's not doubling. Here is my Search Results component that I have showing up (it's bound to a redux state variable to show):

```javascript
var SearchResults = ({ isVisible, isLoading, noResults }) => {
    var content = null;

    if (isLoading) {
        content = <Loading />;
    } else {
        if (noResults) {
            content = (
                <View style={styles.noResults}>
                    <NoResults />
                </View>
            )
        } else {
            content = (
                <View style={styles.resultsContent}>
                    <SearchResultsFilters />
                    <SearchResultsContent />
                </View>
            )
        }
    }

    return isVisible ? (
        <BlurView style={styles.container} blurAmount={2} blurType="dark">
            {content}
        </BlurView>
    ) : null;
};
```
Every time the `content` inside of the `BlurView` changes, that when it seems to double. The modal only opens once - hence the `BlurView` itself only loads once. If you're interested in doing a screenshare, let me know. It might be easier for you to diagnose in person. Let me know if you have any thoughts.

**Comment by simonas-notcat** [comment] 2017-01-06 11:16
I'm facing the same problem :(

**Comment by Kureev** [comment] 2017-01-06 11:25
Can someone make a simple test project? Or at least a way to reproduce the issue.

**Comment by simonas-notcat** [comment] 2017-01-06 14:16
Here is my example project that demonstrated this bug. I'm using:
		"react": "^15.3.2",
		"react-native": "0.39.0",
		"react-native-blur": "1.1.2"

https://github.com/simonas-notcat/react-native-blur-example

Maybe this bug is fixed in the latest version ...

**Comment by Kureev** [comment] 2017-01-06 21:10
Just checked your repo: with react-native@0.40 + react-native-blur@2.0.0 - the issue is not there anymore. Please, consider upgrade to the latest versions and everything will be 👌 . 

Closing this issue as it's fixed in the latest version.

**Closed by Kureev** 2017-01-06 21:10 UTC
