### ISSUE TITLE
Performance of BlurView during scroll

### ISSUE THREAD

**Issue by macrostart** [react-native-community/react-native-blur#46] opened 2016-01-15 11:08 UTC
I'm using multiple BlurView items in one view and I'm hitting performance problems.

I have a list where each item contains: a scaled-down `<Image>`, a `<Blur View>` and [icons](https://github.com/oblador/react-native-vector-icons).
When I scroll my view the perceived framerate drops significantly. Occasionally I see slight flickers in the `<BlurView>` items, as if they were being updated during scroll.

The FPS drops start being visible even in small lists (e.g. 6 elements). They occur both in the simulator and on the device. The issue happens when using `<ScrollView>` and with a `<ListView>` as well. I've experimented with the `shouldRasterizeIOS` [View property](https://facebook.github.io/react-native/docs/view.html#shouldrasterizeios), but couldn't get it to improve the situation.

**Comment by grabbou** [comment] 2016-01-17 18:04
That's very interesting since that view is just a direct mapping to native version, so there should not be any performance issues as far as I am concerned. 

@brentvatne, sorry for disturbing, but would you mind enlightening us on that? Can that be the case inside ScrollView?

**Comment by brentvatne** [comment] 2016-01-18 20:17
`shouldRasterizeIOS` is definitely what you should be using here, if you post some code I can try to suggest where you should be using it

**Comment by StuartMorris0** [comment] 2016-10-20 18:24
Did anyone find an answer for this? I think @grabbou is right that it just uses the native blur view from iOS.

The problem is that the blur is completed on the main thread and therefore the scrolling of a table view (list view) causes some drops in frames.

**Comment by Kureev** [comment] 2017-01-06 10:55
Is it still an actual issue we should solve?

**Comment by morelazers** [comment] 2017-01-09 00:13
@Kureev I'm getting big framedrops on Android with devmode off while using BlurView inside `react-native-gifted-chat`.

I can't test a release build because of another issue at the moment.

**Comment by Kureev** [comment] 2017-01-09 09:41
So if I understand correctly, it's not about our library, right? Can I close it then?

**Comment by morelazers** [comment] 2017-01-09 11:51
@Kureev Yeah - I think OP's issue was probably elsewhere.

**Closed** 2017-01-09 13:12 UTC
Labels: feedback needed
